### ISSUE TITLE
file utility to fits: html format detection bug

### ISSUE THREAD

**Issue by derDaywalker** [harvard-lts/fits#95] opened 2016-06-10 15:16 UTC
Hi

up until version 0.10.2 (and even 1.0.0-RC1) there is a bug regarding parsing file utility's format for text/html. 
Minimal example "test.html" with content:

> <style ...

Although this is not a valid HTML file the bug applies to valid HTML files as well! Check file utility's format and mime type:

> file -b -e cdf test.html: (format)
>   HTML document, ASCII text
> file -b -e cdf --mime test.html: (mime)
>   text/html; charset=us-ascii

If I only use file utility in fits (disable all other tools, except fileinfo + file utilty) I get the following result:

```
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.10.2" timestamp="10.06.16 15:43">
  <identification status="UNKNOWN">
    <identity format="" mimetype="text/html" toolname="FITS" toolversion="0.10.2">
      <tool toolname="file utility" toolversion="5.14" />
    </identity>
  </identification>
 ...
  <toolOutput>
    <tool name="file utility" version="5.14">
      <fileUtilityOutput xmlns="">
        <rawOutput>HTML document, ASCII text
text/html; charset=us-ascii</rawOutput>
        <mimetype>text/html</mimetype>
        <format>Plain text</format>
        <charset>US-ASCII</charset>
      </fileUtilityOutput>
    </tool>
```
Fits reports format ="" but the raw output shows, that it is a HTML document. 
If all tools are enabled file utility's result is discarded by fits:
```

<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.10.2" timestamp="10.06.16 15:44">
  <identification>
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="0.10.2">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="Jhove" toolversion="1.11" />
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">x-fmt/111</externalIdentifier>
    </identity>
  </identification>
   ....
  <toolOutput>
    ....
    </tool>
    <tool name="file utility" version="5.14">
      <fileUtilityOutput xmlns="">
        <rawOutput>HTML document, ASCII text
text/html; charset=us-ascii</rawOutput>
        <mimetype>text/html</mimetype>
        <format>Plain text</format>
        <charset>US-ASCII</charset>
      </fileUtilityOutput>
    </tool>
```

The bug is a combination of fileutility_to_fits.xslt and fits FileUtility.java (edu.harvard.hul.ois.fits.tools.fileutility).
extractInfo()-method within FileUtility.java lines 133 - 147:
```

133		//if mime indicates plain text
134		if(execMimeOut.startsWith("text/") && execMimeOut.contains("charset=")) {
135			//mime = "text/plain";
136			mime = execMimeOut.substring(0,execMimeOut.indexOf("; charset="));
137			charset = execMimeOut.substring(execMimeOut.indexOf("=")+1);
138			charset = charset.toUpperCase();
139			/*if(execOut.contains("ASCII text") ||
140					execOut.contains("Unicode text, UTF-32") ||
141					execOut.contains("UTF-8 Unicode") ||
142					execOut.contains("UTF-16 Unicode") ||
143					execOut.contains("Non-ISO extended-ASCII text") ||
144					execOut.contains("ISO-8859")) {
145				format = "Plain text";	
146			}*/
147			format = "Plain text";
```

Because mime type is text/html, thus mime type starts with "text/" (line 134) the format gets hardcoded to "Plain text" (line 147). Now the problem is, that regarding fileutility_to_fits.xslt (starting at line 214) the format has to be "HTML document text" (line 217), but is in fact hardcoded to "Plain text". Therefore there is a mismatch, resulting that the format is empty:

```
214    <!--  HTML -->                          
215        <xsl:when test="$mime='text/html'">     
216                <xsl:attribute name="format">   
217                        <xsl:if test="$format='HTML document text'">
218                                <xsl:value-of select="string('Hypertext Markup Language')"/>
219                        </xsl:if>               
220                </xsl:attribute> 
221        </xsl:when> 
```

**A quickfix might be to add a additional xsl test for fileutility_to_fits.xslt, in order to test for the hardcoded plain text format if mime type is text/html (line 220 - 222):**

```
214    <!--  HTML -->                          
215    <xsl:when test="$mime='text/html'">     
216            <xsl:attribute name="format">   
217                    <xsl:if test="$format='HTML document text'">
218                            <xsl:value-of select="string('Hypertext Markup Language')"/>
219                    </xsl:if>               
220                    <xsl:if test="$format='Plain text'"> 
221                            <xsl:value-of select="$format"/>
222                    </xsl:if>               
223            </xsl:attribute>                
224    </xsl:when>
```

Fits result after the quickfix (format is now "Plain text"):
```
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.10.2" timestamp="10.06.16 16:01">
  <identification status="SINGLE_RESULT">
    <identity format="Plain text" mimetype="text/html" toolname="FITS" toolversion="0.10.2">
      <tool toolname="file utility" toolversion="5.14" />
    </identity>
  </identification>
```

And with all tools enabled (conflict, because of different mimetype):
```
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.10.2" timestamp="10.06.16 15:49">
  <identification status="CONFLICT">
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="0.10.2">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="Jhove" toolversion="1.11" />
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">x-fmt/111</externalIdentifier>
    </identity>
    <identity format="Plain text" mimetype="text/html" toolname="FITS" toolversion="0.10.2">
      <tool toolname="file utility" toolversion="5.14" />
    </identity>
  </identification>
```
A better fix might be to not hardcode the format for all text/... to Plain text.

**Comment by daveneiman** [comment] 2016-06-13 13:24
Thanks for this detailed report. We will put it into our bug tracking system.
Alternatively, it would be hugely helpful if you forked the FITS project, create a feature branch containing your proposed fix, and then generate a pull request on the 'dev' branch of FITS. This will result in a faster turnaround in improving FITS.
As a new FITS release will be coming out shortly, this proposed fix would go into a subsequent release.

**Comment by derDaywalker** [comment] 2016-06-15 13:46
Ok, I've submitted a pull request for a slightly modified proposed fix. But I've realized, that there is another problem. If the HTML file is valid, everything works perfect. But if the file is not valid, as shown by my minimal example the overall result is not correct as fits tosses out the correct result from the other tools.
                                                                                
Example file:                                                                   

> <style ...   

                                                                   
                                                                                
Result without file utility:                                                    
                                                                                
```
<?xml version="1.0" encoding="UTF-8"?>                                          
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.0.0" timestamp="15.06.16 12:07">
  <identification>                                                              
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="1.0.0">
      <tool toolname="Droid" toolversion="6.1.5" />                             
      <tool toolname="Jhove" toolversion="1.11" />                              
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">x-fmt/111</externalIdentifier>
    </identity>                                                                 
  </identification>
```                                                                   
                                                                                
Debug output:
                                                  
```
DEBUG - OISConsolidator:126 - tossing FFIdent identification because of invalid identification
DEBUG - OISConsolidator:126 - tossing TikaTool identification because of invalid identification
DEBUG - Fits:417 - Outputting results
```                    
                                                                                
Here FFIdent and TikaTool isn't included, because of invalid identification.       
                                                                                
Result with file utility (with fix):                                            
                                                                                
```
<?xml version="1.0" encoding="UTF-8"?>                                          
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.0.0" timestamp="15.06.16 11:54"> 
  <identification status="SINGLE_RESULT">                                       
    <identity format="Hypertext Markup Language" mimetype="text/html" toolname="FITS" toolversion="1.0.0">
      <tool toolname="file utility" toolversion="5.25" />                       
    </identity>                                                                 
  </identification>
```

Debug log:                                                                      
                                                                                
```
DEBUG - OISConsolidator:126 - tossing FFIdent identification because of invalid identification
DEBUG - OISConsolidator:126 - tossing TikaTool identification because of invalid identification
DEBUG - OISConsolidator:424 - Hypertext Markup Language is more specific than Plain text tossing out FITS 
DEBUG - Fits:417 - Outputting results
```                   
                                                                                
Here OISConsolidator tosses out FITS result because 'Hypertext Markup Language is more specific than Plain text'. But the problem is, that Droid and Jhove reports mimetype 'text/plain' and format 'plain text' which is different than 'text/html' and 'Hypertext Markup Language'. In my opinion there shouldn't be a single result but a conflict result, because both, format + mimetype from Droid and Jhove is different than from file utility.

**Comment by andreagoethals** [comment] 2016-06-15 14:17
I think that it is throwing out the Plain text results by design. In the fits_format_tree.xml configuration file we have it configured to recognize that the format Hypertext Markup Language is more specific than Plain text (meaning that the tools are all technically correct but we want the more specific one reported). So in this case it won't report a format conflict. 

<branch format="Plain text">
		<branch format="Extensible Markup Language">
			<branch format="Scalable Vector Graphics (SVG)"/>
		</branch>
		<branch format="Hypertext Markup Language"/>
		<branch format="Postscript"/>
	</branch>

**Comment by derDaywalker** [comment] 2016-06-16 12:28
Ok, I see your point. In general I totally agree. If all tools are correct and one tool is more specific than the others, than it's a good idea to report the more specific format.

> (meaning that the tools are all technically correct but we want the more specific one reported)
In this very special case file utility doesn't report a technically correct result, whereas the other two do. But I understand, that on a technical perspective this is a hard decision, because one can't know if the tool reports a correct result. I think this problem is only solvable if we prioritize tools, e.g. if they also validates the files than the result might be more trustworthy than from a tool without validation. But since only a few tools validates the file, this is not an option.

**Comment by daveneiman** [comment] 2016-09-08 19:17
Resolved by [Pull Request 102](https://github.com/harvard-lts/fits/pull/102).

**Closed by daveneiman** 2016-09-08 19:17 UTC
